### ISSUE TITLE
Cocktails in Ingredients are warped

### ISSUE THREAD

**Issue by MickLesk** [BaristaStudio/PocketBar#35]
Hey!

Nice Project, i follow this Project since a few Days.
I have an idea for this project, if you want to hear it, feel free to contact me.

Reproduce:
1. Go to the Ingredients-Tab
2. Choose e.g. "Amaretto"
3. Scroll Down and Tab "See Cocktails with Amaretto"
4. the Pictures are distorted

**Comment by francinelucca** [comment]
Hi MickLesk!
Glad to hear you've been looking into our project and you are liking what you see!
Would love to hear your ideas, you can reach me at francinelucca@hotmail.com, looking forward to hear from you.

Regarding your issue, we'd first like to thank you for submitting it, we wouldn't have noticed otherwise. In this sense, we've changed the fill aspect of the Image so it doesn't stretch out so weirdly and we've also allowed the photo to occupy more room, that should take care of it, please do check it out.
* Fix Commit : d6e3816788ef989338990df8ecaa79beb998e985

With that, we're marking the issue as closed.
Thanks again,
Francine
