### ISSUE TITLE
(Some) images load very slowly

### ISSUE THREAD

**Issue by MickLesk** [BaristaStudio/PocketBar#36]
Hey,

it's me again.

Reproduce:
1. Click the Glasses Tab
2. Chooste e.g. Shot glass
3.1 Site loading slow (sometimes about 5 Secounds - or alert "something wents wrong"? )
3.2 Images load very slow (Scroll fast down -> Sometimes about 5 secounds too) 

Is that a web request? Because the pages load very slowly with slow internet (e.g. Edge or 3G), here it can come also more often to the message that something went wrong.

Desired solution would be a waiting popup or similar.
Or check whether the internet is fast or slow.

**Comment by francinelucca** [comment]
Hello Again MickLesk!
Thank you for submitting this issue as well, since reading this message we've implemented a library that allows the images to load faster, please be so kind to test the application again, the issue should now be taken care of.
* Fix Commit: bb765cfd2c410a8c3d30fb4ce11bf18024f210b0
Regards,
Francine
